feat(pool): handle UREP-020 and track reputation of unstaked entities
alchemyplatform/rundler pull request #522
Opened 2023-12-04 21:23 UTC by alex-miao

Closes #454, closes #354

## Proposed Changes

  - Track reputation of all entities
  - Move `SAME_SENDER_MEMPOOL_COUNT` check out from `PoolInner` into `UoPool`
  - Do UREP-020 check in the same pool read lock as `SAME_SENDER_MEMPOOL_COUNT` check
  - Fix bug where we increment instead of decrement the reputation of an entity for an unmined transaction

2023-12-04 21:38 UTC, dancoombs commented on crates/pool/src/mempool/error.rs
>      MaxOperationsReached(usize, Address),
I think this is fine, its descriptive enough for both

2023-12-04 21:46 UTC, alex-miao commented on crates/pool/src/mempool/reputation.rs
> +            self.params.inclusion_rate_factor * included / seen + std::cmp::min(included, 10_000)
I honestly think this formula doesn't really make sense, not sure why we need this middle term `self.params.inclusion_rate_factor * included / seen` cause it's some number between 0 and 10, but you already have this constant term `self.params.same_unstaked_entity_mempool_count` that is equal to 10 and its really this `std::cmp::min(included, 10_000)` term that dominates if you do have `included` ops. Also in the [spec](https://github.com/eth-infinitism/account-abstraction/blob/6ade7f1cdb4a0ea1328f5ea8edbfb5fab65deebd/eip/EIPS/eip-aa-rules.md?plain=1#L256) the formula has a hanging parenthesis, so not sure if what's written is what is intended.

2023-12-04 21:46 UTC, dancoombs commented on bin/rundler/src/cli/pool.rs
> +        env = "SAME_SENDER_MEMPOOL_COUNT",
Planning on moving this to `ChainSpec` (when I get around to it)

2023-12-04 21:49 UTC, dancoombs commented on crates/pool/src/mempool/uo_pool.rs
>                  0
Lets add tests for this new constraint. Both for UREP-10 and UREP-20

2023-12-04 21:50 UTC, dancoombs commented on crates/pool/src/mempool/uo_pool.rs
> +        // Check sender count in mempool. If sender has too many operations, must be staked
This would probably explain why `test_max_allowed_ops_unstaked_sender` is failing currently

2023-12-04 21:56 UTC, dancoombs commented on crates/pool/src/mempool/reputation.rs
> +            self.params.inclusion_rate_factor * included / seen + std::cmp::min(included, 10_000)
I'll follow up with them. Seems odd.

2023-12-04 22:08 UTC, alex-miao commented on crates/pool/src/mempool/mod.rs
> +        unstaked_entities.into_iter()
Not sure there is a clean way to do that since we have to pull this info from `EntityInfos`, which has each entity as a field in a struct so I think we just have to check each field one by one. On another note, this function might actually be better suited to be under `EntityInfos` than `PoolOperation`.

2023-12-04 22:16 UTC, dancoombs commented on crates/pool/src/mempool/mod.rs
> +        unstaked_entities.into_iter()
Don't we have `self.entity_infos`? This has the same lifetime as self so you should be able to capture self in the iterator.

2023-12-04 23:17 UTC, alex-miao commented on crates/pool/src/mempool/pool.rs
> -    fn too_many_ops() {
This is no longer relevant at the `pool.rs` level, will replicate this test in `uo_pool.rs`.

2024-01-19 20:55 UTC, dancoombs commented on crates/pool/src/mempool/mod.rs
> +        unstaked_entities.into_iter()
Our entity types really annoy me. We Have `EntityInfo` and `Entity` that have different meanings. We should clean this up. Can you add a ticket?

2024-01-19 20:58 UTC, dancoombs commented on crates/pool/src/mempool/mod.rs
> +        unstaked_entities.into_iter()
In the meantime, how about this:

On `EntityInfos` in `simulation.rs`:
```rust
    /// entities
    pub fn entities(&'_ self) -> impl Iterator<Item = (EntityType, EntityInfo)> + '_ {
        EntityType::iter().filter_map(|t| self.get(t).map(|info| (t, info)))
    }
```

Then on `PoolOperation` here:
```rust
    pub fn staked_entities(&'_ self) -> impl Iterator<Item = Entity> + '_ {
        self.entity_infos.entities().filter_map(|(t, entity)| {
            if self.requires_stake(t) {
                Entity::new(t, entity.address).into()
            } else {
                None
            }
        })
    }

    pub fn unstaked_entities(&'_ self) -> impl Iterator<Item = Entity> + '_ {
        self.entity_infos.entities().filter_map(|(t, entity)| {
            if entity.is_staked {
                None
            } else {
                Entity::new(t, entity.address).into()
            }
        })
    }
```

2024-01-19 21:04 UTC, dancoombs commented on crates/pool/src/mempool/mod.rs
> +        unstaked_entities.into_iter()
Might as well also remove `entity_address` and then 

```rust
    pub fn contains_entity(&self, entity: &Entity) -> bool {
        if let Some(e) = self.entity_infos.get(entity.kind) {
            e.address == entity.address
        } else {
            false
        }
    }
```

2024-01-19 21:08 UTC, dancoombs commented on crates/pool/src/mempool/reputation.rs
> +            self.params.inclusion_rate_factor * included / seen + std::cmp::min(included, 10_000)
Lets leave this with the word of the spec for now

2024-01-19 21:10 UTC, dancoombs reviewed
Lets make sure this is as close to compliant with the latest ERC-7562, while still passing all tests on the commit we've pegged to.

If there are changes in ERC-7562 that cause failures, lets capture them as tickets so we know to update them when we move to a new spec test commit.

One more small nit on the PR to fix up the entities stuff.

2024-01-19 21:16 UTC, 0xfourzerofour commented
Do these changes fix those errors we spoke about in the spec tests?

2024-01-26 11:53 UTC, dancoombs commented on bin/rundler/src/cli/pool.rs
> +        default_value = "10"
Was this the issue that caused the tests to fail?

2024-01-26 11:57 UTC, dancoombs commented on crates/pool/src/mempool/uo_pool.rs
> +        // Check sender count in mempool. If sender has too many operations, must be staked
Can this check happen prior to simulation? As a rule of thumb we want to front load any checks that can be preformed prior to simulation.

2024-01-26 11:59 UTC, dancoombs commented on crates/pool/src/mempool/uo_pool.rs
> +        // Check sender count in mempool. If sender has too many operations, must be staked
The sender, paymaster and factory entities can be extracted prior to simulation for sure. Aggregators are annoying in that they require running the account's validation function.

If this change is too big for this PR lets add a ticket to clean up.

2024-01-26 12:00 UTC, dancoombs requested changes
One last comment and then this is good to go. Can you squash to a single commit?

2024-01-26 19:50 UTC, alex-miao commented on bin/rundler/src/cli/pool.rs
> +        default_value = "10"
No this is unrelated to the test failing since the issue in the test was that 12 blocks passed which is still greater than the correct default.

2024-01-26 20:12 UTC, alex-miao commented on crates/pool/src/mempool/uo_pool.rs
> +        // Check sender count in mempool. If sender has too many operations, must be staked
Added a ticket for this here: https://github.com/alchemyplatform/rundler/issues/571. I think splitting out getting entity staking state and simulation would be beneficial, even for our current simulation flow and removing the need for `EntityInfos` to be returned by `SimulationError`.

2024-01-26 23:27 UTC, 0xfourzerofour commented
@dancoombs I enabled squash and merge after that chat the other day, will use the PR title as the commit message

2024-01-27 15:52 UTC, dancoombs approved these changes

2024-01-27 15:52 UTC, dancoombs commented on bin/rundler/src/cli/pool.rs
> +        default_value = "10"
Got it!

2024-01-29 07:00 UTC, merged