A 7702 support implmentation.
alchemyplatform/rundler pull request #923
Opened 2024-12-02 18:31 UTC by andysim3d

## Proposed Changes
it only works for unsafe mode now, other testnet lacking support of `debug_traceCall`. 
  -
  -
  -

2024-12-02 18:31 UTC, andysim3d commented
a step of #839

2024-12-12 21:52 UTC, dancoombs commented on bin/rundler/chain_specs/mekong.toml
> +id = 7078815900
Remove this file, can be configured via CLI

2024-12-12 21:52 UTC, dancoombs commented on bin/rundler/chain_specs/odessey.toml
> +id = 911867
Same here, remove

2024-12-12 21:57 UTC, dancoombs commented on crates/pool/src/server/remote/protos.rs
> +            }),
Can you DRY this logic? Looks like its here twice. You can implement a `TryFrom` I think

2024-12-12 22:00 UTC, dancoombs commented on crates/rpc/src/types/v0_6.rs
> +    contract_address: Option<Address>,
I think we might need to be more specific than `contract_address` here. What about `delegation_contract_address` or something thats clearly 7702 specific?

2024-12-12 22:01 UTC, dancoombs commented on crates/rpc/src/types/v0_7.rs
> +    contract_address: Option<Address>,
Same comment here on naming

2024-12-12 22:02 UTC, dancoombs commented on crates/sim/src/estimation/estimate_call_gas.rs
> +            apply_7702_overrides(&mut state_override, op.sender(), contract_address);
nit: we typically leave at least som name spacing when importing functions. It makes it clear that the function lives in another file. So here `authoirzation_utils :: apply_7702_overrides `

2024-12-12 22:03 UTC, dancoombs commented on crates/utils/src/authoirzation_utils.rs
> +// This file is part of Rundler.
Typo in the file name

2024-12-12 22:03 UTC, dancoombs commented on crates/utils/src/lib.rs
> +pub mod authoirzation_utils;
Typo here

2024-12-12 22:05 UTC, dancoombs commented on crates/types/src/user_operation/v0_7.rs
> +                s: U256::from(0),
What is this used for?

2024-12-12 22:07 UTC, dancoombs commented on crates/types/src/user_operation/v0_6.rs
> +            s: U256::from(0),
What is this used for? My understanding is that we don't need the authorization because during estimation we just use state overrides to set the code

2024-12-12 22:15 UTC, dancoombs commented on crates/task/src/grpc/protos.rs
> +}
Is there a reason why we need these? Could we instead just use `uint8` and `uint64` in the protobuf?

2024-12-12 22:16 UTC, dancoombs commented on crates/sim/src/precheck.rs
> +        // very hacky, should revisit later.
How so?

2024-12-12 22:17 UTC, dancoombs commented on crates/sim/src/precheck.rs
>          if op.factory().is_none() {
We should probably ensure that a 7702 UO doesn't have a factory set since they're not compatible.

2024-12-12 22:17 UTC, dancoombs commented on crates/sim/src/estimation/v0_7.rs
> +            apply_7702_overrides(&mut local_override, op.sender, *au);
Same nit here

2024-12-12 22:17 UTC, dancoombs commented on crates/sim/src/estimation/v0_6.rs
> +            apply_7702_overrides(&mut local_override, op.sender, *au);
Same nit

2024-12-12 22:20 UTC, dancoombs commented on crates/sim/src/estimation/estimate_verification_gas.rs
> +        let authorization_list_gas = match op.authorization_tuple() {
I don't think this is the correct place for this. The authorization list setting doesn't happen during the verification phase, so its not subject to the verificationGasLimit.

This gas should be added to the preVerificationGas.

I'd guess that the bundler is losing tokens when its sending 7702 transactions without accounting for PVG this way.

2024-12-12 22:20 UTC, dancoombs commented on crates/sim/src/estimation/estimate_verification_gas.rs
> +                // TODO(andy): if sca_address is 0x0, should remove code there.
What is this TODO?

2024-12-12 22:22 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_6.rs
> +            .overrides(&override_7702)
Why are we using an override here vs using a 7702 eth call?

2024-12-12 22:24 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_6.rs
> +            override_7702,
How come this one doesn't have `.with_authorization_list(authorization_list)` but the aggregator version below does?

Also, why do you need the override if you have the authorization list?

2024-12-12 22:25 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_7.rs
> +use std::vec;
Same questions in this file as in the v0.6 file

2024-12-12 22:26 UTC, dancoombs requested changes
Great work! I think the biggest concern here is the handling of the 7702 gas should be moved to preVerificationGas. We should also check if the estimateGas RPC field naming conforms with what the 4337 team is implementing in their tests.

2024-12-13 01:50 UTC, andysim3d commented on crates/rpc/src/types/v0_6.rs
> +    contract_address: Option<Address>,
humm I didn't notice their proposal change the name [authorizationContract](https://hackmd.io/WJtBdwvnT5yLq90F7UilIQ). how does it sounds?

2024-12-13 02:01 UTC, andysim3d commented on crates/types/src/user_operation/v0_6.rs
> +            s: U256::from(0),
We pass the authorization, at least the contract address(other fields are 0 by default) here, so estimator knows what 7702 override to apply.

2024-12-13 02:09 UTC, andysim3d commented on crates/provider/src/alloy/entry_point/v0_6.rs
> +            .overrides(&override_7702)
we can't, or at least shoulnd't use 7702 eath call at gas estimation phase. I assume user don't need to sign authorization tuple during gas estimation phase. without signed authorization tuple, we can't make eth_call with signed authorization tuple.

2024-12-13 02:10 UTC, andysim3d commented on crates/provider/src/alloy/entry_point/v0_6.rs
> +            override_7702,
oops, good catch, I missed the this one.

2024-12-13 02:25 UTC, andysim3d commented on crates/task/src/grpc/protos.rs
> +}
well protos compiles all to Vec<u8>. impl those traits simplifies the work of serialize & deserialize logic.

2024-12-13 03:27 UTC, andysim3d commented
> Great work! I think the biggest concern here is the handling of the 7702 gas should be moved to preVerificationGas. We should also check if the estimateGas RPC field naming conforms with what the 4337 team is implementing in their tests.

for the 4337 - I left a comment to confirm the structure. https://github.com/eth-infinitism/bundler-spec-tests/pull/120#discussion_r1883202383. hope we could resolve the comment asap.

2024-12-13 15:51 UTC, dancoombs commented on crates/rpc/src/types/v0_6.rs
> +    contract_address: Option<Address>,
I like that much better

2024-12-13 15:53 UTC, dancoombs commented on crates/types/src/user_operation/v0_6.rs
> +            s: U256::from(0),
Ah okay, this is a way to convert the user operation from the estimation RPC version to a normal UO for estimation - the signature is not actually needed during estimation. Understood!

2024-12-13 15:54 UTC, dancoombs commented on crates/task/src/grpc/protos.rs
> +}
Does it? Don't we use `uint64` elsewhere in our protos? Would like to stay consistent.

2024-12-13 15:56 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_6.rs
> +            .overrides(&override_7702)
I don't believe this `call_handle_ops` function is used during estimation. In fact, it can't be because a normal handle ops call would fail if the signature isn't valid, so dummy signatures wouldn't work.

I believe this function is only used by the bundle builder to ensure validity of the final bundle. We should double check exactly where its used. But for `handleOps` its safe to assume that all signatures are valid, including authorization tuples.

2024-12-13 16:00 UTC, dancoombs commented
Any idea why compliance is failing?

2024-12-13 16:30 UTC, andysim3d commented
> Any idea why compliance is failing?

yes it is because I add the new field but not mark as optional, so some spec test failed. fixing now.

2024-12-13 16:49 UTC, andysim3d commented on crates/task/src/grpc/protos.rs
> +}
Done.

2024-12-13 16:49 UTC, andysim3d commented on crates/sim/src/estimation/estimate_verification_gas.rs
> +        let authorization_list_gas = match op.authorization_tuple() {
done

2024-12-13 22:09 UTC, dancoombs commented on crates/pool/src/server/remote/protos.rs
> +            .map(|authorization| Authorization::try_from(authorization.clone()).unwrap());
Should this be `.unwrap()` or `?`

2024-12-13 22:09 UTC, dancoombs commented on crates/pool/src/server/remote/protos.rs
> +            .map(|authorization| Authorization::try_from(authorization.clone()).unwrap());
Should this be .unwrap() or ?

2024-12-13 22:10 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_6.rs
> +        let mut local_state = state_override.clone();
Why is this clone needed? Can we just do `mut state_override` in the function signature?

2024-12-13 22:11 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_7.rs
> +use std::vec;
nit: what is this import used for? `vec!` shouldn't need to be imported

2024-12-13 22:13 UTC, dancoombs commented on crates/task/src/grpc/protos.rs
> -
nit: lets add this back so we don't have a single whitespace change in this file

2024-12-13 23:51 UTC, andysim3d commented on crates/pool/src/server/remote/protos.rs
> +            .map(|authorization| Authorization::try_from(authorization.clone()).unwrap());
this is intended to keep as option<authorization>. if a UO w/o authorization_tuple, it should not fail here.

2024-12-13 23:51 UTC, andysim3d commented on crates/pool/src/server/remote/protos.rs
> +            .map(|authorization| Authorization::try_from(authorization.clone()).unwrap());
same ^

2024-12-15 15:27 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_6.rs
> +            .max_priority_fee_per_gas(gas_fees.max_priority_fee_per_gas)
nit: can we put this back to the  way it was?

2024-12-15 15:28 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_6.rs
> +        let authorization_tuple = op.authorization_tuple.clone();
Do you need to clone here? Looks like you can do this by reference

2024-12-15 15:29 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_7.rs
> +        let au = user_op.authorization_tuple().clone();
Same question here, does this need to be a clone?

2024-12-15 15:31 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_7.rs
> +        let authorization_tuple = user_op.authorization_tuple.clone();
```suggestion
        if let Some(authorization) = &user_op.authorization_tuple {
            authorization_utils::apply_7702_overrides(
                &mut override_ep,
                user_op.sender(),
                authorization.address.clone(), // clone just the part you need here
            );
        }
```

2024-12-15 15:31 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_7.rs
> +        let authorization_tuple = op.authorization_tuple.clone();
Same quesetion

2024-12-15 15:33 UTC, dancoombs commented on crates/sim/src/precheck.rs
> +        };
Is there a reason why you did this here and not in the `estimate_pre_verification_gas` function? So we don't need to duplicate this logic in 3 places.

2024-12-15 15:35 UTC, dancoombs commented on crates/provider/src/alloy/entry_point/v0_6.rs
`calc_da_gas` below needs the `.with_authorization_list` portion if the UO contains an auth list, to ensure that we're charging for that DA calldata. Worth checking there rest of the codebase to see if there are other places this is missing.

2024-12-15 15:37 UTC, dancoombs commented on crates/pool/src/server/remote/protos.rs
> +            .map(|authorization| Authorization::try_from(authorization.clone()).unwrap());
Got it, so we have a check for this elsewhere? There's no way for a UO that has an authorization tuple couldn't convert that tuple into a protobuf tuple? This `unwrap()` is on the protobuf conversion

2024-12-16 18:59 UTC, dancoombs commented on crates/sim/src/precheck.rs
> +        };
Fix LGTM

2024-12-16 19:27 UTC, dancoombs approved these changes
🚢 Great work!

2024-12-16 20:06 UTC, merged