chore: bump reth deps
alchemyplatform/rundler pull request #933
Opened 2024-12-11 18:43 UTC by 0xOsiris

[Closes/Fixes] #

## Proposed Changes

This PR bumps the `reth-tasks` dependency in `rundler` to `v1.1.4`. This makes `rundler` crates compatible with projects depending on the latest version of Reth.

2024-12-11 19:23 UTC, dancoombs commented
@0xOsiris is the large diff here because of a `cargo update`? Were there further conflicts in when trying to upgrade reth-tasks?

2024-12-11 19:48 UTC, 0xOsiris commented
> @0xOsiris is the large diff here because of a `cargo update`? Were there further conflicts in when trying to upgrade reth-tasks?

Yes, `cargo build` initially failed but a `cargo update` patched the lock file

2024-12-12 14:48 UTC, dancoombs commented
Looks like the `cargo update` pulled in some changes that broke our lints.

It seems alloy has deprecated some fields, we're actively updating alloy in another PR, so this should get fixed once that merges https://github.com/alchemyplatform/rundler/pull/930.

For the Cargo Deny failure, its likely we just have to add `Unicode-3.0` to our allowlist. Let me check internally.

2024-12-16 16:42 UTC, dancoombs commented
Update here, we're still figuring out what we need to do (if anything) to change our license to incorporate these denied crates. Trying to get this done ASAP.

2024-12-18 17:59 UTC, dancoombs commented
This should clear up the deny issue, also includes the `cargo update` so you can just add the reth bump https://github.com/alchemyplatform/rundler/pull/942

2024-12-19 21:51 UTC, 0xOsiris commented on test/spec-tests/v0_6/bundler-spec-tests
Not sure how this happened 😅

2024-12-19 21:53 UTC, 0xOsiris commented
> This should clear up the deny issue, also includes the `cargo update` so you can just add the reth bump #942

Awesome, just merged upstream!

2024-12-19 22:15 UTC, dancoombs requested changes
Looks like you have changes to the git submodules. You should revert that change back to head and then run `git update submodules` to get your local updated and this diff should go away.

(I hate submodules and we're looking at ways to remove these, but they're currently very useful for testing)

2024-12-20 21:15 UTC, dancoombs approved these changes
Thanks for dealing with all the back-and-forth here!

2025-01-05 19:22 UTC, merged